# Generated by Django 5.1 on 2024-10-15 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 21, 57, 37, 256387, tzinfo=datetime.timezone.utc)),
        ),
    ]
