# Generated by Django 5.1 on 2024-11-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='coin',
            field=models.CharField(choices=[('USD', 'Dólar'), ('BTC', 'Bitcoin'), ('EUR', 'Euro')], max_length=10),
        ),
    ]
