# Generated by Django 5.1 on 2024-11-18 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_offert_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 18, 57, 16, 943561)),
        ),
    ]
