# Generated by Django 5.1 on 2024-11-25 18:35

import api.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[api.model_validators.validate_phone])),
                ('CNPJ', models.CharField(max_length=20, unique=True, validators=[api.model_validators.validate_cnpj])),
            ],
        ),
        migrations.CreateModel(
            name='FeedBacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
