# Generated by Django 5.1 on 2024-11-06 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 22, 56, 52, 452287, tzinfo=datetime.timezone.utc)),
        ),
    ]
