# Generated by Django 5.1 on 2024-11-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CNPJ',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
