# Generated by Django 5.1 on 2024-11-25 22:14

import api.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CNPJ',
            field=models.CharField(max_length=20, unique=True, validators=[api.model_validators.validate_cnpj]),
        ),
    ]
