# Generated by Django 5.1 on 2024-11-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='stars',
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
